### ISSUE TITLE
"it doesn't work"

### ISSUE THREAD

**Issue by lemmy04** [TheLastProject/RaiseToAnswer#8]
Sorry, but that really is all I have: "It doesn't work".

I tap the "test" button, and I get a popup saying "hold the phone to your ear", I do that, nothing happens.
I can't accept calls by holding the phone to my ear either.

No errors, "accept phone calls" permissions are granted.

Device is a Samsung S8+ running Android 9, rooted with Magisk.

Any ideas?

**Comment by lemmy04** [comment]
Before i forget: apk comes from f-droid, not google play.

**Comment by TheLastProject** [comment]
Nothing happens at all? Not even 2 beeps? Can you try increasing your music volume? You should at least hear 2 beeps and when holding it to your ear 3 more.

The latest release actually shows a dialog box after success instead of just beeping to make things clearer, but F-Droid still hasn't pushed out new app updates (they've been really slow with that lately). Please consider trying the latest .apk here from GitHub Releases as it should make the test result clearer.

**Comment by lemmy04** [comment]
ok part of it was the media volume - somehow it was down at 0, now the test works.
taking a call still doesn't...

**Comment by lemmy04** [comment]
the 2.0.1 apk from here works like a charm. Now how can we get f-droid and google play to pick up the latest version?

**Comment by TheLastProject** [comment]
I honestly don't understand why it would work on 2.0.1, because I didn't really change any code at that part. I find it very interesting that, so far, every "it doesn't work" report I got was from a Samsung device. I wonder if they do some "battery optimization" stuff or so that's more extreme than other manufacturers and break it there.

Regarding the update, I already submitted it to Google Play and F-Droid picked it up 4 days ago: https://gitlab.com/fdroid/fdroiddata/-/commit/88143cf71aeb141e8dc2775e49c5df0863134da3.

For Google Play it is "being reviewed" which can "take up to 7 days". It is however already available on the Beta track. For F-Droid, app updates don't become available until someone manually signs the APKs which I believe only one person on the team can do so that just takes some time, no ETA there. So it's just a waiting game there, really.

**Comment by TheLastProject** [comment]
Google Play updated a few hours ago, still waiting for F-Droid.

**Comment by TheLastProject** [comment]
Someone else reported a similar issue and 2.0.2 fixed it for them. I'm closing this issue now as there's nothing I can do to make F-Droid be faster. Thank you for all your patience and help in improving stuff, feel free to open issues in the future if you ever have issues again.

**Comment by gabsoftware** [comment]
I confirm that the 1.3.5 release from F-Droid does not work on Lineageos 16, OnePlus 5T. But it does work well with the 2.0.2 release.

**Comment by lemmy04** [comment]
by now f-droid and play both at least have 2.0.1...
